function conds_mat = conditions_SPT_ESOP(out_dir)

ep = readtable([out_dir '/eprime_summary.csv'],'Delimiter','comma');
ep = readtable([out_dir '/eprime_summary.csv'], ...
	'Format',repmat('%q',1,size(ep,2)));

% Combine target and foil trials. Scramble condition has no targets
names = {'Scene';'People';'Scramble'};

scene_ons = [ ...
	eval(ep.OnsetsSec{strcmp(ep.Condition,'Scene_Target')}) ...
	eval(ep.OnsetsSec{strcmp(ep.Condition,'Scene_Foil')}) ...
	];
scene_dur = [ ...
	eval(ep.DurationsSec{strcmp(ep.Condition,'Scene_Target')}) ...
	eval(ep.DurationsSec{strcmp(ep.Condition,'Scene_Foil')}) ...
	];

people_ons = [ ...
	eval(ep.OnsetsSec{strcmp(ep.Condition,'People_Target')}) ...
	eval(ep.OnsetsSec{strcmp(ep.Condition,'People_Foil')}) ...
	];
people_dur = [ ...
	eval(ep.DurationsSec{strcmp(ep.Condition,'People_Target')}) ...
	eval(ep.DurationsSec{strcmp(ep.Condition,'People_Foil')}) ...
	];

scramble_ons = [ ...
	eval(ep.OnsetsSec{strcmp(ep.Condition,'Scramble_Foil')}) ...
	];
scramble_dur = [ ...
	eval(ep.DurationsSec{strcmp(ep.Condition,'Scramble_Foil')}) ...
	];

onsets = {scene_ons;people_ons;scramble_ons};

durations = {scene_dur;people_dur;scramble_dur};

conds_mat = [out_dir '/conds.mat'];
save(conds_mat,'names','onsets','durations');

